name: Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  package-tests:
    runs-on: ubuntu-latest
    name: Package tests
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install shortuuid django
    - run: python runtests.py
